apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-operator-prototype
spec:
  replicas: 1
  selector:
    matchLabels:
      name: monitoring-operator-prototype
  template:
    metadata:
      labels:
        name: monitoring-operator-prototype
    spec:
      serviceAccountName: monitoring-operator-prototype
      containers:
        - name: monitoring-operator-prototype
          # Replace this with the built image name
          image: quay.io/mvala/monitoring-operator-prototype
          command:
          - monitoring-operator-prototype
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "monitoring-operator-prototype"
